version: '3'

tasks:
  default:
    desc: Show all available tasks
    cmds:
      - task --list

  build:
    desc: Build the binaries
    cmds:
      - go build -o bin/reconswarm ./main.go

  test:
    desc: Run tests
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  staticcheck:
    desc: Run staticcheck
    cmds:
      - task: install-staticcheck
      - staticcheck ./...

  install-staticcheck:
    desc: Install staticcheck if not present
    cmds:
      - command -v staticcheck >/dev/null || GOTOOLCHAIN=local go install honnef.co/go/tools/cmd/staticcheck@latest
    run: once

  lint:
    desc: Run golangci-lint
    cmds:
      - task: install-golangci
      - golangci-lint run

  install-golangci:
    desc: Install golangci-lint if not present
    cmds:
      - command -v golangci-lint >/dev/null || GOTOOLCHAIN=local go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    run: once

  ci:
    desc: Run all CI checks
    deps: [vet, staticcheck, lint, test]

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - gofmt -w .

  proto:
    desc: Generate Go code from proto files
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/reconswarm.proto

