# ReconSwarm Pipeline Example - Nuclei
# This example demonstrates how to configure a pipeline with Nuclei scanner

pipeline:
  # Executing pre commands on the server before running pipeline on workers 
  pre_commands: []

  targets:
    - value: "example.com"
      type: crtsh
    - value: ["somesite.com", "anothersite.com"]
      type: list
  stages:
    - name: "Run nuclei and collect results"
      ignore_fail: true
      type: exec
      steps:
        - "docker run --rm -v /opt/recon:/data -v {{.Targets.filepath}}:/data/hosts.txt projectdiscovery/nuclei:latest -severity medium,high,critical -l /data/hosts.txt -json-export /data/nuclei-{{.Worker.Name}}.json"
    - name: "Copy results file"
      type: sync
      src: "/opt/recon/nuclei-{{.Worker.Name}}.json"
      dest: "./results/{{.PipelineID}}/nuclei-{{.Worker.Name}}.json"
    # Example: Sync entire directory recursively
    # - name: "Copy all results"
    #   type: sync
    #   src: "/opt/recon"
    #   dest: "./results/{{.Worker.Name}}"

  # Executing post commands on the server when all stages completes across workers 
  post_commands:
    - "cd ./results/{{.PipelineID}} && find . -name '*.json' -type f -size +2c | xargs cat  | jq > found-{{.PipelineID}}.json"
