// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/reconswarm.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReconSwarm_RunPipeline_FullMethodName   = "/reconswarm.ReconSwarm/RunPipeline"
	ReconSwarm_GetPipeline_FullMethodName   = "/reconswarm.ReconSwarm/GetPipeline"
	ReconSwarm_ListPipelines_FullMethodName = "/reconswarm.ReconSwarm/ListPipelines"
)

// ReconSwarmClient is the client API for ReconSwarm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReconSwarmClient interface {
	RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (*RunPipelineResponse, error)
	GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*GetPipelineResponse, error)
	ListPipelines(ctx context.Context, in *ListPipelinesRequest, opts ...grpc.CallOption) (*ListPipelinesResponse, error)
}

type reconSwarmClient struct {
	cc grpc.ClientConnInterface
}

func NewReconSwarmClient(cc grpc.ClientConnInterface) ReconSwarmClient {
	return &reconSwarmClient{cc}
}

func (c *reconSwarmClient) RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (*RunPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunPipelineResponse)
	err := c.cc.Invoke(ctx, ReconSwarm_RunPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconSwarmClient) GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*GetPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineResponse)
	err := c.cc.Invoke(ctx, ReconSwarm_GetPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reconSwarmClient) ListPipelines(ctx context.Context, in *ListPipelinesRequest, opts ...grpc.CallOption) (*ListPipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPipelinesResponse)
	err := c.cc.Invoke(ctx, ReconSwarm_ListPipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReconSwarmServer is the server API for ReconSwarm service.
// All implementations must embed UnimplementedReconSwarmServer
// for forward compatibility.
type ReconSwarmServer interface {
	RunPipeline(context.Context, *RunPipelineRequest) (*RunPipelineResponse, error)
	GetPipeline(context.Context, *GetPipelineRequest) (*GetPipelineResponse, error)
	ListPipelines(context.Context, *ListPipelinesRequest) (*ListPipelinesResponse, error)
	mustEmbedUnimplementedReconSwarmServer()
}

// UnimplementedReconSwarmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReconSwarmServer struct{}

func (UnimplementedReconSwarmServer) RunPipeline(context.Context, *RunPipelineRequest) (*RunPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunPipeline not implemented")
}
func (UnimplementedReconSwarmServer) GetPipeline(context.Context, *GetPipelineRequest) (*GetPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipeline not implemented")
}
func (UnimplementedReconSwarmServer) ListPipelines(context.Context, *ListPipelinesRequest) (*ListPipelinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPipelines not implemented")
}
func (UnimplementedReconSwarmServer) mustEmbedUnimplementedReconSwarmServer() {}
func (UnimplementedReconSwarmServer) testEmbeddedByValue()                    {}

// UnsafeReconSwarmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReconSwarmServer will
// result in compilation errors.
type UnsafeReconSwarmServer interface {
	mustEmbedUnimplementedReconSwarmServer()
}

func RegisterReconSwarmServer(s grpc.ServiceRegistrar, srv ReconSwarmServer) {
	// If the following call panics, it indicates UnimplementedReconSwarmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReconSwarm_ServiceDesc, srv)
}

func _ReconSwarm_RunPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconSwarmServer).RunPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconSwarm_RunPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconSwarmServer).RunPipeline(ctx, req.(*RunPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconSwarm_GetPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconSwarmServer).GetPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconSwarm_GetPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconSwarmServer).GetPipeline(ctx, req.(*GetPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReconSwarm_ListPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconSwarmServer).ListPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReconSwarm_ListPipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconSwarmServer).ListPipelines(ctx, req.(*ListPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReconSwarm_ServiceDesc is the grpc.ServiceDesc for ReconSwarm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReconSwarm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reconswarm.ReconSwarm",
	HandlerType: (*ReconSwarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunPipeline",
			Handler:    _ReconSwarm_RunPipeline_Handler,
		},
		{
			MethodName: "GetPipeline",
			Handler:    _ReconSwarm_GetPipeline_Handler,
		},
		{
			MethodName: "ListPipelines",
			Handler:    _ReconSwarm_ListPipelines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/reconswarm.proto",
}
