// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/reconswarm.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pipeline represents the full pipeline configuration.
// This mirrors the YAML structure used for defining pipelines.
type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Stages        []*Stage               `protobuf:"bytes,2,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_api_reconswarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{0}
}

func (x *Pipeline) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Pipeline) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

// Target defines a source of targets for the pipeline.
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                  // crtsh, list, external_list, shell_output
	StringValue   string                 `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"` // used for crtsh, external_list, shell_output
	ListValue     []string               `protobuf:"bytes,3,rep,name=list_value,json=listValue,proto3" json:"list_value,omitempty"`       // used for list type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_api_reconswarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Target) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *Target) GetListValue() []string {
	if x != nil {
		return x.ListValue
	}
	return nil
}

// Stage defines a single pipeline stage.
type Stage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*Stage_Exec
	//	*Stage_Sync
	Config        isStage_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_api_reconswarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{2}
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetConfig() isStage_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Stage) GetExec() *ExecStage {
	if x != nil {
		if x, ok := x.Config.(*Stage_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Stage) GetSync() *SyncStage {
	if x != nil {
		if x, ok := x.Config.(*Stage_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

type isStage_Config interface {
	isStage_Config()
}

type Stage_Exec struct {
	Exec *ExecStage `protobuf:"bytes,2,opt,name=exec,proto3,oneof"`
}

type Stage_Sync struct {
	Sync *SyncStage `protobuf:"bytes,3,opt,name=sync,proto3,oneof"`
}

func (*Stage_Exec) isStage_Config() {}

func (*Stage_Sync) isStage_Config() {}

// ExecStage executes a sequence of shell commands on the worker.
type ExecStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []string               `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStage) Reset() {
	*x = ExecStage{}
	mi := &file_api_reconswarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStage) ProtoMessage() {}

func (x *ExecStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStage.ProtoReflect.Descriptor instead.
func (*ExecStage) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{3}
}

func (x *ExecStage) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

// SyncStage synchronizes files between remote worker and local machine.
type SyncStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStage) Reset() {
	*x = SyncStage{}
	mi := &file_api_reconswarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStage) ProtoMessage() {}

func (x *SyncStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStage.ProtoReflect.Descriptor instead.
func (*SyncStage) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{4}
}

func (x *SyncStage) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *SyncStage) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

// Worker represents a worker node status.
type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentTask   string                 `protobuf:"bytes,4,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_api_reconswarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{5}
}

func (x *Worker) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Worker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Worker) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

type RunPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_api_reconswarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{6}
}

func (x *RunPipelineRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type RunPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineResponse) Reset() {
	*x = RunPipelineResponse{}
	mi := &file_api_reconswarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineResponse) ProtoMessage() {}

func (x *RunPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineResponse.ProtoReflect.Descriptor instead.
func (*RunPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{7}
}

func (x *RunPipelineResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_api_reconswarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{8}
}

func (x *GetPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetPipelineResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PipelineId      string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Pipeline        *Pipeline              `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	TotalStages     int32                  `protobuf:"varint,5,opt,name=total_stages,json=totalStages,proto3" json:"total_stages,omitempty"`
	CompletedStages int32                  `protobuf:"varint,6,opt,name=completed_stages,json=completedStages,proto3" json:"completed_stages,omitempty"`
	Workers         []*Worker              `protobuf:"bytes,7,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPipelineResponse) Reset() {
	*x = GetPipelineResponse{}
	mi := &file_api_reconswarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineResponse) ProtoMessage() {}

func (x *GetPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{9}
}

func (x *GetPipelineResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *GetPipelineResponse) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GetPipelineResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPipelineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetPipelineResponse) GetTotalStages() int32 {
	if x != nil {
		return x.TotalStages
	}
	return 0
}

func (x *GetPipelineResponse) GetCompletedStages() int32 {
	if x != nil {
		return x.CompletedStages
	}
	return 0
}

func (x *GetPipelineResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

type ListPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesRequest) Reset() {
	*x = ListPipelinesRequest{}
	mi := &file_api_reconswarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesRequest) ProtoMessage() {}

func (x *ListPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{10}
}

func (x *ListPipelinesRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListPipelinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipelines     []*GetPipelineResponse `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResponse) Reset() {
	*x = ListPipelinesResponse{}
	mi := &file_api_reconswarm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResponse) ProtoMessage() {}

func (x *ListPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{11}
}

func (x *ListPipelinesResponse) GetPipelines() []*GetPipelineResponse {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

var File_api_reconswarm_proto protoreflect.FileDescriptor

const file_api_reconswarm_proto_rawDesc = "" +
	"\n" +
	"\x14api/reconswarm.proto\x12\n" +
	"reconswarm\"c\n" +
	"\bPipeline\x12,\n" +
	"\atargets\x18\x01 \x03(\v2\x12.reconswarm.TargetR\atargets\x12)\n" +
	"\x06stages\x18\x02 \x03(\v2\x11.reconswarm.StageR\x06stages\"^\n" +
	"\x06Target\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fstring_value\x18\x02 \x01(\tR\vstringValue\x12\x1d\n" +
	"\n" +
	"list_value\x18\x03 \x03(\tR\tlistValue\"\x7f\n" +
	"\x05Stage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04exec\x18\x02 \x01(\v2\x15.reconswarm.ExecStageH\x00R\x04exec\x12+\n" +
	"\x04sync\x18\x03 \x01(\v2\x15.reconswarm.SyncStageH\x00R\x04syncB\b\n" +
	"\x06config\"!\n" +
	"\tExecStage\x12\x14\n" +
	"\x05steps\x18\x01 \x03(\tR\x05steps\"1\n" +
	"\tSyncStage\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\"t\n" +
	"\x06Worker\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_task\x18\x04 \x01(\tR\vcurrentTask\"F\n" +
	"\x12RunPipelineRequest\x120\n" +
	"\bpipeline\x18\x01 \x01(\v2\x14.reconswarm.PipelineR\bpipeline\"6\n" +
	"\x13RunPipelineResponse\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"5\n" +
	"\x12GetPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"\x92\x02\n" +
	"\x13GetPipelineResponse\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x120\n" +
	"\bpipeline\x18\x02 \x01(\v2\x14.reconswarm.PipelineR\bpipeline\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\ftotal_stages\x18\x05 \x01(\x05R\vtotalStages\x12)\n" +
	"\x10completed_stages\x18\x06 \x01(\x05R\x0fcompletedStages\x12,\n" +
	"\aworkers\x18\a \x03(\v2\x12.reconswarm.WorkerR\aworkers\";\n" +
	"\x14ListPipelinesRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\"V\n" +
	"\x15ListPipelinesResponse\x12=\n" +
	"\tpipelines\x18\x01 \x03(\v2\x1f.reconswarm.GetPipelineResponseR\tpipelines2\x82\x02\n" +
	"\n" +
	"ReconSwarm\x12N\n" +
	"\vRunPipeline\x12\x1e.reconswarm.RunPipelineRequest\x1a\x1f.reconswarm.RunPipelineResponse\x12N\n" +
	"\vGetPipeline\x12\x1e.reconswarm.GetPipelineRequest\x1a\x1f.reconswarm.GetPipelineResponse\x12T\n" +
	"\rListPipelines\x12 .reconswarm.ListPipelinesRequest\x1a!.reconswarm.ListPipelinesResponseB\x10Z\x0ereconswarm/apib\x06proto3"

var (
	file_api_reconswarm_proto_rawDescOnce sync.Once
	file_api_reconswarm_proto_rawDescData []byte
)

func file_api_reconswarm_proto_rawDescGZIP() []byte {
	file_api_reconswarm_proto_rawDescOnce.Do(func() {
		file_api_reconswarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reconswarm_proto_rawDesc), len(file_api_reconswarm_proto_rawDesc)))
	})
	return file_api_reconswarm_proto_rawDescData
}

var file_api_reconswarm_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_reconswarm_proto_goTypes = []any{
	(*Pipeline)(nil),              // 0: reconswarm.Pipeline
	(*Target)(nil),                // 1: reconswarm.Target
	(*Stage)(nil),                 // 2: reconswarm.Stage
	(*ExecStage)(nil),             // 3: reconswarm.ExecStage
	(*SyncStage)(nil),             // 4: reconswarm.SyncStage
	(*Worker)(nil),                // 5: reconswarm.Worker
	(*RunPipelineRequest)(nil),    // 6: reconswarm.RunPipelineRequest
	(*RunPipelineResponse)(nil),   // 7: reconswarm.RunPipelineResponse
	(*GetPipelineRequest)(nil),    // 8: reconswarm.GetPipelineRequest
	(*GetPipelineResponse)(nil),   // 9: reconswarm.GetPipelineResponse
	(*ListPipelinesRequest)(nil),  // 10: reconswarm.ListPipelinesRequest
	(*ListPipelinesResponse)(nil), // 11: reconswarm.ListPipelinesResponse
}
var file_api_reconswarm_proto_depIdxs = []int32{
	1,  // 0: reconswarm.Pipeline.targets:type_name -> reconswarm.Target
	2,  // 1: reconswarm.Pipeline.stages:type_name -> reconswarm.Stage
	3,  // 2: reconswarm.Stage.exec:type_name -> reconswarm.ExecStage
	4,  // 3: reconswarm.Stage.sync:type_name -> reconswarm.SyncStage
	0,  // 4: reconswarm.RunPipelineRequest.pipeline:type_name -> reconswarm.Pipeline
	0,  // 5: reconswarm.GetPipelineResponse.pipeline:type_name -> reconswarm.Pipeline
	5,  // 6: reconswarm.GetPipelineResponse.workers:type_name -> reconswarm.Worker
	9,  // 7: reconswarm.ListPipelinesResponse.pipelines:type_name -> reconswarm.GetPipelineResponse
	6,  // 8: reconswarm.ReconSwarm.RunPipeline:input_type -> reconswarm.RunPipelineRequest
	8,  // 9: reconswarm.ReconSwarm.GetPipeline:input_type -> reconswarm.GetPipelineRequest
	10, // 10: reconswarm.ReconSwarm.ListPipelines:input_type -> reconswarm.ListPipelinesRequest
	7,  // 11: reconswarm.ReconSwarm.RunPipeline:output_type -> reconswarm.RunPipelineResponse
	9,  // 12: reconswarm.ReconSwarm.GetPipeline:output_type -> reconswarm.GetPipelineResponse
	11, // 13: reconswarm.ReconSwarm.ListPipelines:output_type -> reconswarm.ListPipelinesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_reconswarm_proto_init() }
func file_api_reconswarm_proto_init() {
	if File_api_reconswarm_proto != nil {
		return
	}
	file_api_reconswarm_proto_msgTypes[2].OneofWrappers = []any{
		(*Stage_Exec)(nil),
		(*Stage_Sync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reconswarm_proto_rawDesc), len(file_api_reconswarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reconswarm_proto_goTypes,
		DependencyIndexes: file_api_reconswarm_proto_depIdxs,
		MessageInfos:      file_api_reconswarm_proto_msgTypes,
	}.Build()
	File_api_reconswarm_proto = out.File
	file_api_reconswarm_proto_goTypes = nil
	file_api_reconswarm_proto_depIdxs = nil
}
