// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/reconswarm.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineYaml  string                 `protobuf:"bytes,1,opt,name=pipeline_yaml,json=pipelineYaml,proto3" json:"pipeline_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_api_reconswarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{0}
}

func (x *RunPipelineRequest) GetPipelineYaml() string {
	if x != nil {
		return x.PipelineYaml
	}
	return ""
}

type RunPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineResponse) Reset() {
	*x = RunPipelineResponse{}
	mi := &file_api_reconswarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineResponse) ProtoMessage() {}

func (x *RunPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineResponse.ProtoReflect.Descriptor instead.
func (*RunPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{1}
}

func (x *RunPipelineResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_reconswarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PipelineId      string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Pending, Running, Completed, Failed
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	TotalStages     int32                  `protobuf:"varint,4,opt,name=total_stages,json=totalStages,proto3" json:"total_stages,omitempty"`
	CompletedStages int32                  `protobuf:"varint,5,opt,name=completed_stages,json=completedStages,proto3" json:"completed_stages,omitempty"`
	Workers         []*WorkerStatus        `protobuf:"bytes,6,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_reconswarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetStatusResponse) GetTotalStages() int32 {
	if x != nil {
		return x.TotalStages
	}
	return 0
}

func (x *GetStatusResponse) GetCompletedStages() int32 {
	if x != nil {
		return x.CompletedStages
	}
	return 0
}

func (x *GetStatusResponse) GetWorkers() []*WorkerStatus {
	if x != nil {
		return x.Workers
	}
	return nil
}

type WorkerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Provisioning, Running, Idle, Terminated
	CurrentTask   string                 `protobuf:"bytes,4,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_api_reconswarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconswarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_api_reconswarm_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerStatus) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

var File_api_reconswarm_proto protoreflect.FileDescriptor

const file_api_reconswarm_proto_rawDesc = "" +
	"\n" +
	"\x14api/reconswarm.proto\x12\n" +
	"reconswarm\"9\n" +
	"\x12RunPipelineRequest\x12#\n" +
	"\rpipeline_yaml\x18\x01 \x01(\tR\fpipelineYaml\"6\n" +
	"\x13RunPipelineResponse\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"3\n" +
	"\x10GetStatusRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"\xe4\x01\n" +
	"\x11GetStatusResponse\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\ftotal_stages\x18\x04 \x01(\x05R\vtotalStages\x12)\n" +
	"\x10completed_stages\x18\x05 \x01(\x05R\x0fcompletedStages\x122\n" +
	"\aworkers\x18\x06 \x03(\v2\x18.reconswarm.WorkerStatusR\aworkers\"z\n" +
	"\fWorkerStatus\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_task\x18\x04 \x01(\tR\vcurrentTask2\xa6\x01\n" +
	"\n" +
	"ReconSwarm\x12N\n" +
	"\vRunPipeline\x12\x1e.reconswarm.RunPipelineRequest\x1a\x1f.reconswarm.RunPipelineResponse\x12H\n" +
	"\tGetStatus\x12\x1c.reconswarm.GetStatusRequest\x1a\x1d.reconswarm.GetStatusResponseB\x10Z\x0ereconswarm/apib\x06proto3"

var (
	file_api_reconswarm_proto_rawDescOnce sync.Once
	file_api_reconswarm_proto_rawDescData []byte
)

func file_api_reconswarm_proto_rawDescGZIP() []byte {
	file_api_reconswarm_proto_rawDescOnce.Do(func() {
		file_api_reconswarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reconswarm_proto_rawDesc), len(file_api_reconswarm_proto_rawDesc)))
	})
	return file_api_reconswarm_proto_rawDescData
}

var file_api_reconswarm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_reconswarm_proto_goTypes = []any{
	(*RunPipelineRequest)(nil),  // 0: reconswarm.RunPipelineRequest
	(*RunPipelineResponse)(nil), // 1: reconswarm.RunPipelineResponse
	(*GetStatusRequest)(nil),    // 2: reconswarm.GetStatusRequest
	(*GetStatusResponse)(nil),   // 3: reconswarm.GetStatusResponse
	(*WorkerStatus)(nil),        // 4: reconswarm.WorkerStatus
}
var file_api_reconswarm_proto_depIdxs = []int32{
	4, // 0: reconswarm.GetStatusResponse.workers:type_name -> reconswarm.WorkerStatus
	0, // 1: reconswarm.ReconSwarm.RunPipeline:input_type -> reconswarm.RunPipelineRequest
	2, // 2: reconswarm.ReconSwarm.GetStatus:input_type -> reconswarm.GetStatusRequest
	1, // 3: reconswarm.ReconSwarm.RunPipeline:output_type -> reconswarm.RunPipelineResponse
	3, // 4: reconswarm.ReconSwarm.GetStatus:output_type -> reconswarm.GetStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_reconswarm_proto_init() }
func file_api_reconswarm_proto_init() {
	if File_api_reconswarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reconswarm_proto_rawDesc), len(file_api_reconswarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reconswarm_proto_goTypes,
		DependencyIndexes: file_api_reconswarm_proto_depIdxs,
		MessageInfos:      file_api_reconswarm_proto_msgTypes,
	}.Build()
	File_api_reconswarm_proto = out.File
	file_api_reconswarm_proto_goTypes = nil
	file_api_reconswarm_proto_depIdxs = nil
}
